ComicPresence.Web/Areas/Dashboard/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicPresence.Web.Areas.Dashboard.Controllers
{
    public class DashBoardController : Controller
    {
        //
        // GET: /Dashboard/DashBoard/

        public ActionResult Index()
        {
            return View();
        }
    }
}

ComicPresence.Web/Areas/Dashboard/Controllers/PartialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicPresence.Web.Areas.Dashboard.Controllers
{
    public class PartialsController : Controller
    {
        public ActionResult TopNavbar()
        {
            return PartialView();
        }
        public ActionResult Sidebar()
        {
            return PartialView();
        }
        public ActionResult Offsidebar()
        {
            return PartialView();
        }
        public ActionResult Footer()
        {
            return PartialView();
        }
        public ActionResult OffsidebarTab1()
        {
            return PartialView();
        }
        public ActionResult OffsidebarTab2()
        {
            return PartialView();
        }
    }
}

ComicPresence.Web/Controllers/BaseController.cs
using System.Web.Mvc;

using ComicPresence.Infrastructure;
using ComicPresence.Model;
using ComicPresence.Model.Repositories;
using ComicPresence.Repositories;
using ComicPresence.Repositories.EF;
using ComicPresence.Repositories.EF.Repositories;

namespace ComicPresence.Web.Controllers
{
    public class BaseController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        public BaseController(): this(new EFUnitOfWorkFactory())
        {

        }

        public BaseController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
        }
    }
}

ComicPresence.Web/Controllers/ComicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using ComicPresence.Infrastructure;
using ComicPresence.Model;
using ComicPresence.Model.Repositories;
using ComicPresence.Repositories;

namespace ComicPresence.Web.Controllers
{
    public class ComicController : BaseController
    {
        private readonly IComicRepository _comicRepository;

        public ComicController(IComicRepository comicRepository)
        {
            _comicRepository = comicRepository;            
        }

        //
        // GET: /Comic/

        public ActionResult Index()
        {
            var comics = _comicRepository.GetAllComics();
            return View(comics);
        }

        public ActionResult Comic(string id)
        {
            return View(_comicRepository.GetComicBySlug(id));
        }

        public ActionResult _ComicDisplay()
        {
            return PartialView(_comicRepository.GetCurrentComic());
        }
    }
}

ComicPresence.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ComicPresence.Web.Controllers
{
    public class HomeController : BaseController
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Examples()
        {
            return View();
        }
    }
}

ComicPresence.Web/Areas/Dashboard/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}

<span>&copy; @DateTime.Now.Year Comic Presence </span>

ComicPresence.Web/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App + jQuery">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>Comic Presence</title>
    <!-- =============== VENDOR STYLES ===============-->
    @Styles.Render("~/dashboard/fontawesome")
    @Styles.Render("~/dashboard/simpleLineIcons")
    @Styles.Render("~/dashboard/animatecss")
    @Styles.Render("~/dashboard/whirl")
    <!-- =============== PAGE VENDOR STYLES =============== -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <!-- ================ Favicon ================ -->
    <link rel="shortcut icon" href="~/Areas/Dashboard/favicon.ico" />
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link href="@Styles.Url("~/Areas/Dashboard/Content/app/css/bootstrap.css")" rel="stylesheet" type="text/css" id="bscss" />
    <!-- =============== APP STYLES ===============-->
    <link href="@Styles.Url("~/Areas/Dashboard/Content/app/css/app.css")" rel="stylesheet" type="text/css" id="maincss" />

</head>
<body class="layout-fixed">
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            @Html.Partial("_TopNavbar")
        </header>
        <!-- sidebar-->
        <aside class="aside">
            @Html.Partial("_Sidebar")
        </aside>
        <!-- offsidebar-->
        <aside class="offsidebar">
            @Html.Partial("_Offsidebar")
        </aside>
        <!-- Main section-->
        <section>
            <!-- Page content-->
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </section>
        <!-- Page footer-->
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>
    @if (IsSectionDefined("BodyArea"))
    {@RenderSection("BodyArea", required: false)}
    <!-- =============== VENDOR SCRIPTS ===============-->
    @Scripts.Render("~/dashboard/modernizr")
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
    @Scripts.Render("~/dashboard/bootstrap")
    @Scripts.Render("~/dashboard/storage")
    @Scripts.Render("~/dashboard/jqueryEasing")
    @Scripts.Render("~/dashboard/animo")
    @Scripts.Render("~/dashboard/slimscroll")
    @Scripts.Render("~/dashboard/screenfull")
    @Scripts.Render("~/dashboard/localize")
    @Scripts.Render("~/dashboard/demoRTL")
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)
    <!-- =============== APP SCRIPTS ===============-->
    @Scripts.Render("~/dashboard/baseScripts")
</body>
</html>

ComicPresence.Web/Areas/Dashboard/Views/Shared/_TopNavbar.cshtml
@{
    Layout = null;
}

<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
        <a href="#/" class="navbar-brand">
            <div class="brand-logo">
                <img src="~/Areas/Dashboard/Content/Images/logo.png" alt="App Logo" class="img-responsive" />
            </div>
            <div class="brand-logo-collapsed">
                <img src="~/Areas/Dashboard/Content/Images/logo-single.png" alt="App Logo" class="img-responsive" />
            </div>
        </a>
    </div>
    <!-- END navbar header-->
    <!-- START Nav wrapper-->
    <div class="nav-wrapper">
        <!-- START Left navbar-->
        <ul class="nav navbar-nav">
            <li>
                <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
                    <em class="fa fa-navicon"></em>
                </a>
                <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                    <em class="fa fa-navicon"></em>
                </a>
            </li>
            <!-- START User avatar toggle-->
            <li>
                <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                <a id="user-block-toggle" href="#user-block" data-toggle="collapse">
                    <em class="icon-user"></em>
                </a>
            </li>
            <!-- END User avatar toggle-->
            <!-- START lock screen-->
            <li>
                <a href="@Url.Action("Lock", "Pages")" title="Lock screen">
                    <em class="icon-lock"></em>
                </a>
            </li>
            <!-- END lock screen-->
        </ul>
        <!-- END Left navbar-->
        <!-- START Right Navbar-->
        <ul class="nav navbar-nav navbar-right">
            <!-- Search icon-->
            <li>
                <a href="#" data-search-open="">
                    <em class="icon-magnifier"></em>
                </a>
            </li>
            <!-- Fullscreen (only desktops)-->
            <li class="visible-lg">
                <a href="#" data-toggle-fullscreen="">
                    <em class="fa fa-expand"></em>
                </a>
            </li>
            <!-- START Alert menu-->
            <li class="dropdown dropdown-list">
                <a href="#" data-toggle="dropdown">
                    <em class="icon-bell"></em>
                    <div class="label label-danger">11</div>
                </a>
                <!-- START Dropdown menu-->
                <ul class="dropdown-menu animated flipInX">
                    <li>
                        <!-- START list group-->
                        <div class="list-group">
                            <!-- list item-->
                            <a href="#" class="list-group-item">
                                <div class="media-box">
                                    <div class="pull-left">
                                        <em class="fa fa-twitter fa-2x text-info"></em>
                                    </div>
                                    <div class="media-box-body clearfix">
                                        <p class="m0">New followers</p>
                                        <p class="m0 text-muted">
                                            <small>1 new follower</small>
                                        </p>
                                    </div>
                                </div>
                            </a>
                            <!-- list item-->
                            <a href="#" class="list-group-item">
                                <div class="media-box">
                                    <div class="pull-left">
                                        <em class="fa fa-envelope fa-2x text-warning"></em>
                                    </div>
                                    <div class="media-box-body clearfix">
                                        <p class="m0">New e-mails</p>
                                        <p class="m0 text-muted">
                                            <small>You have 10 new emails</small>
                                        </p>
                                    </div>
                                </div>
                            </a>
                            <!-- list item-->
                            <a href="#" class="list-group-item">
                                <div class="media-box">
                                    <div class="pull-left">
                                        <em class="fa fa-tasks fa-2x text-success"></em>
                                    </div>
                                    <div class="media-box-body clearfix">
                                        <p class="m0">Pending Tasks</p>
                                        <p class="m0 text-muted">
                                            <small>11 pending task</small>
                                        </p>
                                    </div>
                                </div>
                            </a>
                            <!-- last list item -->
                            <a href="#" class="list-group-item">
                                <small>More notifications</small>
                                <span class="label label-danger pull-right">14</span>
                            </a>
                        </div>
                        <!-- END list group-->
                    </li>
                </ul>
                <!-- END Dropdown menu-->
            </li>
            <!-- END Alert menu-->
            <!-- START Contacts button-->
            <li>
                <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
                    <em class="icon-notebook"></em>
                </a>
            </li>
            <!-- END Contacts menu-->
        </ul>
        <!-- END Right Navbar-->
    </div>
    <!-- END Nav wrapper-->
    <!-- START Search form-->
    <form role="search" action="search.html" class="navbar-form">
        <div class="form-group has-feedback">
            <input type="text" placeholder="Type and hit enter ..." class="form-control" />
            <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
        </div>
        <button type="submit" class="hidden btn btn-default">Submit</button>
    </form>
    <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

ComicPresence.Web/Views/Comic/Comic.cshtml
@model ComicPresence.Model.dtoComic

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.Title</h3>
    </div>
    <div class="panel-body">
        <img src="@Url.Content(Model.ComicImage)" alt="@Model.Title" />
    </div>
</div>
    

ComicPresence.Web/Views/Comic/Index.cshtml
@model IEnumerable<ComicPresence.Model.dtoComic>

@{
    ViewBag.Title = "Comics";
}

<div class="row">
        <div class="col-lg-12">
            <div class="'page-header">
                <h1 id="comics">Comics</h1>
            </div>
            <div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ComicID)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AuthorID)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IllustratorID)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.WriterID)
                            </th>
                            <th>
                                Author Name
                            </th>
                            <th>
                                    Chapter
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.BookID)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ComicDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ComicSlug)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model) {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ComicID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AuthorID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IllustratorName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.WriterID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.WriterName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Chapter.ChapterTitle)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BookID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>        
                                <td>
                                    @Html.DisplayFor(modelItem => item.ComicDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ComicSlug)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
</div>

ComicPresence.Web/Views/Comic/_ComicDisplay.cshtml
@model ComicPresence.Model.dtoComic

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.Title</h3>
    </div>
    <div class="panel-body">
        <img src="@Url.Content(Model.ComicImage)" alt="@Model.Title" />
    </div>
</div>

ComicPresence.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="page-header">
    <h1>Comic Presence <small>by Nodoubt Designs&reg;</small></h1>
    <p>Sleek, intuitive, and powerful front-end framework for faster and easier web comic development.</p>
</div>
<div class="container">
    <div>
        @{Html.RenderAction("_ComicDisplay", "Comic");}
    </div>
</div>
<ul>
    <li>
        <a href="https://bitbucket.org/nodoubt223rd/comicpresence-v2" target="_blank">Bitbucket project</a>
    </li>
    <li>
        @Html.ActionLink("Comics", "Index")
    </li>
    <li>Version 2.0.0
    </li>
</ul>

ComicPresence.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using System.Configuration;

@using ComicPresence.Web.Helpers
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ConfigurationManager.AppSettings["siteName"].ToString() &bull; @ViewBag.Title </title>

    @Styles.Render("~/css")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="@Url.Action("Index", "Home")">@ConfigurationManager.AppSettings["siteName"].ToString()</a>
                <ul class="nav">
                    @Html.MenuLink("Home", "Index", "Home")
					@Html.MenuLink("Comics", "Index", "Comic")
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <noscript>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Warning!</strong> Please enable JavaScript in your browser!
            </div>
        </noscript>

        <div class="row">
            @if (IsSectionDefined("sidebar"))
            {
                <div class="span2">
                    @RenderSection("sidebar", required: false)
                </div>
            }

            <div id="content" @(IsSectionDefined("sidebar") ? Html.Raw("class=span10") : Html.Raw("class=span12"))>
                @if (IsSectionDefined("featured"))
                {
                    <div>
                        <div class="hero-unit">
                            @RenderSection("featured", required: false)
                        </div>
                    </div>
                }
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>

        <div class="row">
			<div class="span12">
                <footer id="footer">
				    &copy; @DateTime.Now.Year.ToString() Nodoubt Designs.
                </footer>
			</div>
        </div>
    </div>
    @Scripts.Render("~/js")
    @RenderSection("scripts", required: false)
</body>
</html>